import { Montserrat } from 'next/font/google'
import Head from 'next/head'
import Layout from '@/components/Layout'
import Image from 'next/image'
import profilePic from "../../public/images/profile/bird.png"
import AnimatedText from '@/components/AnimatedText'
import Link from 'next/link';
import { LinkArrow } from '@/components/icons'
import HireMe from '@/components/HireMe'
import lightBulb from "../../public/images/svgs/miscellaneous_icons_1.svg"
import TransitionEffect from '@/components/TransitionEffect'

const mont = Montserrat({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Masha Designs | Portfolio</title>
        <meta name='description' content="Generated by MashaDesigns" />
      </Head>
      <TransitionEffect />
      <main className='flex items-center text-black w-full min-h-screen dark:text-light' >
        <Layout className='pt-0 md:pt-16 sm:px-8'>

          <div className='flex items-center justify-between w-full lg:flex-col'>
            <div className='w-1/2 md:w-full'>
              <Image src={profilePic} alt="Home Image" className='w-full h-auto lg:hidden md:inline-block md:w-full'
                priority
                sizes='(max-width: 1200px) 50vw,
              50vw' />
            </div>
            <div className='w-1/2 flex flex-col items-center self-center lg:w-full lg:text-center'>
              <AnimatedText text="Code Craft: Turning Ideas into Digital Realities." className='!text-6xl !text-left xl:!text-5xl
              lg:!text-center lg:!text-6xl md:!text-5xl sm:!text-3xl' />
              <p className='my-6 text-base font-medium md:text-sm sm:text-xs'>
                As a Web Developer, I am dedicated to turning ideas into innovative web applications.
                Explore my latest projects and articles, showcasing my expertise in web development.

              </p>
              <div className='flex items-center self-start mt-2 lg:self-center'>
                <Link href="/kevCV.pdf" target={'_blank'}
                  className='flex items-center bg-black text-white p-2.5 px-6
                rounded-lg text-lg font-semibold hover:bg-white hover:text-black
                border-2 border-solid border-transparent hover:border-black
                dark:bg-light dark:text-dark
                hover:dark:bg-dark hover:dark:text-light
                hover:dark:border-light md:px-4 md:text-base'
                  download={true}
                >Resume <LinkArrow className={"w-6 ml-1"} />

                </Link>
                <Link href="mailto:njugunak.kevin@gmail.com" target={'_blank'}
                  className='ml-4 text-lg font-medium capitalize text-black underline dark:text-light md:text-base'
                >Contact</Link>
              </div>
            </div>
          </div>

        </Layout>
        <HireMe />
        <div className='absolute right-8 bottom8 inline-block w-24 md:hidden'>
          <Image src={lightBulb} alt="MashaDesigns" className='w-full h-auto' />
        </div>
      </main>
    </>
  )
}
